name: Build for GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install NPM dependencies
      run: npm i typescript ts-loader sass sass-loader css-loader style-loader @types/jquery webpack webpack-cli --save-dev

    - name: Build webpack
      run: npx webpack

    - name: Delete .gitignore
      run: rm .gitignore

    - name: New .gitignore
      run: echo "node_modules/ src/ webpack.config.js tsconfig.json package-lock.json .github/" > .gitignore

    - name: Checkout Git
      run: git checkout -b gh-pages
    
    - name: Remove from git
      run: git rm -rf --cached *

    - name: Set upstream
      run: git branch --set-upstream-to=origin/master gh-pages

    - uses: EndBug/add-and-commit@v7
      with:
        add: '["dist/main.js", "*.html"]'
        author_name: TheDutchMC
        author_email: github@thedutchmc.nl
        branch: gh-pages
        message: 'Automatic build for GH-Pages'
        push: origin gh-pages
        signoff: true